export const reducerCases = {
    SET_SELLER: "SET_SELLER",
    SWITCH_MODE: "SWITCH_MODE",
    SET_SERVICE_DATA: "SET_SERVICE_DATA",
    HAS_USER_ORDERED_SERVICE: "HAS_USER_ORDERED_SERVICE",
    ADD_REVIEW: "ADD_REVIEW",
  };